matrix:
  include:
    - os: linux
      language: python
      env: ATOM_CHANNEL=stable
    - os: linux
      language: python
      env: ATOM_CHANNEL=beta
    - os: osx
      language: generic
      env: ATOM_CHANNEL=stable
      before_install:
        - brew update
        - brew install python || brew upgrade python
    - os: osx
      language: generic
      env: ATOM_CHANNEL=beta
      before_install:
        - brew update
        - brew install python || brew upgrade python

install:
  - pip install pylama pylama_pylint

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

notifications:
  email:
    on_success: never
    on_failure: change

sudo: false

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - fakeroot
      - git
      - libsecret-1-dev

git:
  depth: 10
