### Project specific config ###
language: python
install:
  - pip install pylama pylama_pylint
jobs:
  include:
    # Test Atom versions
    - stage: test
      os: linux
      python: "2.7"
      env: ATOM_CHANNEL=stable
    - stage: test
      os: linux
      python: "3.7"
      env: ATOM_CHANNEL=beta
    - stage: test
      os: osx
      python: "2.7.15"
      env: ATOM_CHANNEL=stable

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - "./build-package.sh"

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

stages:
  - test
